jobs: 4
matrix:
- name: Markdown
  aspell:
    lang: en
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'src/**/*.md'
  default_encoding: utf-8
